- include: build_hosts_file.yml
- include: celery.yml

#########################
### Stop all services ###
#########################

- name: Stop OPV service
  service:
    name: "opv-{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - api
    - dm

- name: Stop Postgresql
  service:
    name: "postgresql"
    state: stopped
    enabled: no

- name: Stop Redis
  service:
    name: "redis-server"
    state: stopped
    enabled: no

- name: Stop Celery worker
  service:
    name: "celery"
    state: stopped
    enabled: no

- name: Stop Flower
  service:
    name: "flower"
    state: stopped
    enabled: no
