- include: build_hosts_file.yml


#########################
### Stop all services ###
#########################

- include: build_hosts_file.yml

- name: Stop airflow services
  service:
    name: "airflow-{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - webserver
    - scheduler
    - flower
    - worker

- name: Stop OPV service
  service:
    name: "opv-{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - api
    - dm

- name: Stop Postgresql
  service:
    name: "postgresql"
    state: stopped
    enabled: no

- name: Stop Redis
  service:
    name: "postgresql"
    state: stopped
    enabled: no

- name: Configure airflow
  template:
    src: airflow.cfg
    dest: /home/opv/airflow/airflow.cfg
    owner: opv
    group: opv
    mode: 0744
