###############
### Ariflow ###
###############

- name: Create Airflow postgresql database
  postgresql_db:
    name: airflow
  become: yes
  become_user: postgres

- name: Create Airflow postgresql user
  postgresql_user:
    db: airflow
    name: airflow
    password: "{{ postgresPasswdAirflow }}"
  become: yes
  become_user: postgres

- name: Configure Postgresql (pg_hba.conf)
  lineinfile:
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    line: "host    airflow         airflow         0.0.0.0/0               md5"
  notify:
  - Restart Postgresql

- meta: flush_handlers

- name: Initialize Airflow db
  shell: source ~/venvs/opv/bin/activate ; airflow initdb
  args:
    executable: /bin/bash
  become: yes
  become_user: opv

- name: Launch airflow master service
  service:
    name: "airflow-{{ item }}"
    state: started
    enabled: yes
  with_items:
    - webserver
    - scheduler
    - flower

- name: Export NFS /home/opv/airflow/dags
  lineinfile:
    dest: /etc/exports
    line: "/home/opv/airflow/dags *(rw,all_squash,anonuid=1000,anongid=1000,sync,no_subtree_check)"
  notify:
  - Reload NFS

- meta: flush_handlers
