################################
### Activate Master Services ###
################################

- name: Start Postgresql
  service:
    name: "postgresql"
    state: started
    enabled: yes

# - name: Start Redis
#   service:
#     name: "redis"
#     state: started
#     enabled: yes
#
# - include: airflow.yml
- include: opv.yml
