- name: Install opensfm dependencies
  apt: name={{ item }} state=present
  with_items:
   - build-essential
   - cmake
   - git
   - libatlas-base-dev
   - libboost-python-dev
   - libeigen3-dev
   - libgoogle-glog-dev
   - libopencv-dev
   - libsuitesparse-dev
   - python-dev
   - python-numpy
   - python-opencv
   - python-pyexiv2
   - python-pyproj
   - python-scipy
   - python-yaml
   - python-pip
   - wget

- name: Extract ceres-solver-1.13.0.tar.gz
  unarchive:
    src: ceres-solver-1.13.0.tar.gz
    dest: /root

# Alors la je me suis pas fait chier mais alors pas du tout du tout. Du pur KISS
- name: Install ceres-solver-1.13.0
  command: cp -rp /root/ceres-solver-1.13.0/usr /.

- name: Extract opengv.tar.gz
  unarchive:
    src: opengv.tar.gz
    dest: /root

# Alors la je me suis pas fait chier mais alors pas du tout du tout. Du pur KISS
- name: Install opengv
  command: cp -rp /root/opengv/usr /.

########################################
### Install opengv in our virtualenv ###
#######################################


- name: Install OpenSfM
  shell: |
    cd /root
    git clone https://github.com/mapillary/OpenSfM
    cd OpenSfM
    pip install -r requirements.txt
    python setup.py build
    python setup.py install
    exit 0
  args:
    executable: /bin/bash
  run_once: true
