- name: Install opensfm dependencies
  apt: name={{ item }} state=present
  with_items:
   - build-essential
   - cmake
   - git
   - libatlas-base-dev
   - libboost-python-dev
   - libeigen3-dev
   - libgoogle-glog-dev
   - libopencv-dev
   - libsuitesparse-dev
   - python-dev
   - python-numpy
   - python-opencv
   - python-pyexiv2
   - python-pyproj
   - python-scipy
   - python-yaml
   - python-pip
   - wget

- name: Create OpenSfM directory
  file:
    path: "/opt/OpenSfM"
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: 0755

- name: Extract ceres-solver-1.10.0.tar.gz
  unarchive:
    src: ceres-solver-1.10.0.tar.gz
    dest: /opt/OpenSfM

# Alors la je me suis pas fait chier mais alors pas du tout du tout. Du pur KISS => Et c'est de la grosse MERDE, Merci de faire un .deb, m'enfin ca reste comme ca pour le moment
- name: Install ceres-solver-1.10.0
  command: cp -rp /opt/OpenSfM/ceres-solver-1.10.0/usr /.

- name: Extract opengv.tar.gz
  unarchive:
    src: opengv.tar.gz
    dest: /opt/OpenSfM

# Alors la je me suis pas fait chier mais alors pas du tout du tout. Du pur KISS  => Et c'est de la grosse MERDE, Merci de faire un .deb, m'enfin ca reste comme ca pour le moment
- name: Install opengv
  command: cp -rp /opt/OpenSfM/opengv/usr /.

########################################
### Install opengv in our virtualenv ###
#######################################


- name: Install OpenSfM
  shell: |
    cd /opt/OpenSfM
    git clone https://github.com/OpenPathView/OpenSfM.git
    cd OpenSfM
    pip install -r requirements.txt
    python setup.py build
    python setup.py install
    exit 0
  args:
    executable: /bin/bash
