#############
### Redis ###
#############

- name: Install redis
  apt: name={{ item }} state=present
  with_items:
    - redis-server

- name: Configure Redis
  replace:
    dest: /etc/redis/redis.conf
    regexp: '^bind 127.0.0.1'
    replace: 'bind 0.0.0.0'
  notify:
    - Restart Redis

- meta: flush_handlers
